name = "FiNeR"
author = "Stefano Zaghi"
copyright = "Copyright © 2016, Stefano Zaghi"
license = "Multiple licenses"
description = "Fortran INI ParseR and generator for FoRtraners"
maintainer = "Stefano Zaghi"
homepage = "https://github.com/szaghi/FiNeR"

[library]
source-dir = "src/lib"

[install]
library = true

[dependencies]
[dependencies.BeFoR64]
git = "https://github.com/szaghi/BeFoR64"
rev = "09b95c08a2ee8995d19cf8551c22b783193f6246"
[dependencies.FACE]
git = "https://github.com/szaghi/FACE"
rev = "3bdabbc7f24843ddde8b3afd1f17c325e8e215c9"
[dependencies.FLAP]
git = "https://github.com/szaghi/FLAP"
rev = "6611e8a25c2a9ab6ef6d9f469218b766653df930"
[dependencies.PENF]
git = "https://github.com/szaghi/PENF"
rev = "65061235982495b158412b70c05b228af4320d94"
[dependencies.StringiFor]
git = "https://github.com/szaghi/StringiFor"
rev = "25570c36964ef49942537af942603962c3f26b68"

[dev-dependencies]
[dev-dependencies.fortran_tester]
git = "https://github.com/pdebuyl/fortran_tester"
