name = "PENF"
author = "Stefano Zaghi"
copyright = "Copyright © 2016, Stefano Zaghi"
license = "Multiple licenses"
description = "Fortran INI ParseR and generator for FoRtraners"
maintainer = "Stefano Zaghi"
homepage = "https://github.com/szaghi/FiNeR"

[library]
source-dir = "src/lib"

[install]
library = true
