name = "PENF"
author = "Stefano Zaghi"
copyright = "Copyright © 2016, Stefano Zaghi"
license = "Multiple licenses"
description = "Fortran INI ParseR and generator for FoRtraners"
maintainer = "Stefano Zaghi"
homepage = "https://github.com/szaghi/FiNeR"

[library]
source-dir = "src/lib"

[install]
library = true

[dependencies]
BeFoR64.git="https://github.com/szaghi/BeFoR64"
FACE.git="https://github.com/szaghi/FACE"
FLAP.git="https://github.com/szaghi/FLAP"
PENF.git="https://github.com/szaghi/PENF"
StringiFor.git="https://github.com/szaghi/StringiFor"
fortran_tester.git="https://github.com/pdebuyl/fortran_tester"

